version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  patient-service:
    build: .
    container_name: patient-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/patientdb
    depends_on:
      - mongo

volumes:
  mongo-data: